export const fieldsData = [
    {
        id: 'name',
        title: 'Name',
        isRequired: true,
        errorMessage: 'Name is required',
        value: '',
        type: 'string',
        placeholder: 'Enter your name',
        step: 0,
    },
    {
        id: 'idNumber',
        title: 'ID Number',
        isRequired: true,
        errorMessage: 'ID number is required',
        value: '',
        type: 'number',
        placeholder: 'Enter your number',
        step: 0,
    },
    {
        id: 'email',
        title: 'Email',
        isRequired: true,
        errorMessage: 'Email is required',
        value: '',
        type: 'email',
        placeholder: 'Enter your email',
        step: 0,
    },
    {
        id: 'birthday',
        title: 'Birth date',
        isRequired: true,
        errorMessage: 'Date of Birth is required',
        value: '',
        type: 'date',
        placeholder: 'Enter your birth date',
        step: 0,
    },
    {
        id: 'cv',
        title: 'Upload CV/Resume',
        isRequired: true,
        errorMessage: 'CV/Resume is required',
        value: '',
        type: 'file',
        placeholder: 'Enter',
        step: 1,
    },
    {
        id: 'department',
        title: 'Department',
        isRequired: true,
        errorMessage: 'Department is required',
        value: '',
        type: 'text',
        placeholder: 'Enter your department',
        step: 1,
    },
    {
        id: 'skills',
        title: 'Skills (optional)',
        isRequired: false,
        errorMessage: '',
        value: '',
        type: 'text',
        placeholder: 'Enter your skills',
        step: 2,
    },
    {
        id: 'terms',
        title: 'I agree to the terms and conditions',
        isRequired: true,
        errorMessage: '',
        value: '',
        type: 'checkbox',
        placeholder: 'Terms and conditions must be accepted',
        step: 2,
    },
];

export const STEP_COUNT = 3;